language: C++ 
dist: xenial

addons:
  apt:
    packages:
      - qt5-default

services:
  - xvfb

script:
  - cd CALCULATORRR/ && qmake QMAKE_CXXFLAGS+=-std=gnu++11
  - make
  - xvfb-run -a ./test/tst_calctest

